### ISSUE TITLE
Utilisateur : authentification et vérification

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#16]
- [x] Si un utilisateur a interrompu le processus d'inscription, il doit pouvoir retrouver son inscription en cours s'il essaye de s'inscrire ou de se connecter avec la même adresse mail

Si l'utilisateur change de n° de tel : 
- [x] Il perd son grade
- [x] son profil redevient non vérifié
- [x] son profil est bloqué si pas de vérification admin dans la semaine
- [x] il lui est demandé de vérifier son n° (sms avec code) 
- [x] Vérifier que le fonctionnement est similaire pour les emails

**Comment by clairezed** [comment]
@MIRADOR-EPINAL J'ai besoin de faire un point clair et un peu subtil sur cette histoire de vérification (attention, concentration), car le système actuel est cohérent mais en contradiction avec ce que j'ai écrit rapidement ci-dessus.

Ci-dessous, j'appelle "statut de vérification" un état interne de l'utilisateur, qui me sert à gérer ses droits, des comportements de l'application. C'est pas un état qui est affiché sur le site.

La vérification d'un utilisateur passe par plusieurs étapes : 
- après son inscription, l'utilisateur n'a vérfié ni son téléphone, ni son mail. Son statut de vérification est `en attente`.
- une fois qu'il a vérifié son mail ET son tel, son statut passe à `infos vérifiées`. L'admin reçoit un mail comme quoi un profil est prêt à être vérifié par lui. Sur le site, le profil de l'utilisateur apparaît toujours comme "non vérifié".
- Si l'admin accepte le profil, le statut de vérification l'utilisateur passe à `vérifié par l'admin`. Sur sa fiche, la mention  "non vérifié" passe à  "vérifié".
- Si l'admin rejette le profil (statut passe à `rejeté par l'admin`), il est bloqué. L'utilisateur ne peut plus se connecter, son profil n'est plus visible, ses événements sont annulés automatiquement.

Là où il y a marges d'interprétation dans le cahier des charges, c'est entre `infos vérifiées` et `vérifié par l'admin`. Voilà comment ça marche actuellement, merci de me dire si c'est bien ce que vous aviez en tête.

## Infos vérifiées 
- à partir du moment où mail et tel son renseigné, le profil peut accéder au site librement. Au bout d'une semaine, il n'est pas bloqué, même si l'admin ne l'a pas vérifié. Ceci afin que l'utilisateur ne soit pas pénalisé par des délais de traitement par l'admin. 
- par contre, son profil apparaît bien aux yeux des autres utilisateurs comme "non vérifié".
- mais c'est ce statut qui est pris en compte pour le grade (si je me fie à ce qui est écrit ici : https://docs.google.com/spreadsheets/d/1reVC2L9-lR4tCVZLD_V3J5xu291eJL53BdUI8k4gasg/edit#gid=307971120)
- on peut donc voir sur la fiche d'un utilisateur à la fois `non vérifié` et grade `expert` par exemple.

## Vérifié par l'admin
- Finalement, actuellement, la seule chose que ce statut change, c'est l'apparition de la mention "vérifié" sur la fiche de l'utilisateur. Et ce, indépendamment du grade.

**Comment by MIRADOR-EPINAL** [comment]
@clairezed 
C'est bien ça Claire 👍 

> bien que s'affiche "non vérifié" sur le profil, du moment que l'adresse mail et le numéro de téléphone ont été validés (le mail en allant dans sa boîte mail cliquer sur le lien, le téléphone en rentrant le code reçu par SMS) ces éléments peuvent servir à monter en grade.

> la procédure de vérification que tu décris est exactement celle qui est prévue et qu'on a choisi (je plaide coupable).
