### ISSUE TITLE
Blocage par un utilisateur

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#18]
- [x] Un utilisateur peut bloquer/débloquer un autre utilisateur : apparition d'une pop up avec select (obligatoire) + texte libre.
- [x] L'admin peut retrouver les blocages dans le backoffice

Le fait de bloquer un utilisateur entrainera :
- [x] Le fait que lorsque l’utilisateur bloqueur lance un événement l’utilisateur bloqué ne le voit pas (Un utilisateur ne peut pas voir un événement créé par qqn qui l’a bloqué)
- [x] Le fait que la présence du bloqué ou du bloqueur sera signalée par pop up lorsque le bloqué ou le bloqueur consulte l’événement en question (“Attention, vous avez bloqué Marc V, voulez-vous maintenir votre inscription”)
- [x] Si je suis participant à un événement, et qu’un bloqué s’inscrit ensuite, je reçois une notification (“Marc V s’est inscrit, souhaitez-vous tjs participer à l’événement ?”)
- [x] Un utilisateur ne peut pas être recherché/vu par  qqn qui l’a bloqué (pour les invitations)

**Comment by clairezed** [comment]
@MIRADOR-EPINAL il faudra me donner les valeurs possibles du select des raisons de blocage (c'est le prochain truc auquel je m'attelle)

**Comment by MIRADOR-EPINAL** [comment]
@clairezed message bien reçu. Je vais tenter de trouver ça ASAP.

**Comment by MIRADOR-EPINAL** [comment]
@clairezed 
J'ai mis une modeste photo de l'imitation du pop-up blocage. 

La pop-up s'ouvre et apparaît:
[titre] Bloquer cette personne

Pourquoi je veux bloquer cette personne (seul l'administrateur d'ensemble peut lire votre commentaire)
[champ de commentaire libre]

Si vous cliquez sur OK, cette personne ne pourra plus:
> vous inviter à des événements
> voir votre profil
> s'inscrire à des événements auxquels vous participez

[bouton] annuler    [bouton] OK


![20180215_110135 1](https://user-images.githubusercontent.com/35603109/36250907-9234625a-123f-11e8-8f58-fc2c5d181b58.jpg)


J'espère que c'est compréhensible

**Comment by clairezed** [comment]
Cool le schéma ! Je crois que je comprends tout :)

Quelques questions complémentaires  : 
- est-ce que l'admin veut garder trace des motifs de blocage, même si l'utilisateur bloqué a entretemps été débloqué ?

**Comment by clairezed** [comment]
Bon, une fois que je vois la question écrite, elle me parait bizarre. C'était la logique de réflexion sur la base de donnée à l'oeuvre. Ce que je prévois de faire : tous les bloquages fait, avec ou sans commentaire, seront retrouvables dans l'admin. Ce qui permettra si un jour on le veut de voir qui a été le + bloqué, etc

**Comment by MIRADOR-EPINAL** [comment]
OK, bah si techniquement tout ça te convient moi ça me convient. L'idée principale de ce blocage est que si un utilisateur est bloqué par plusieurs personnes c'est un indice pour commencer à se demander si on ne devrait pas supprimer son compte.
espérons que l'on en arrivera jamais à des extrémités comme celle-ci.

**Comment by clairezed** [comment]
Quelques retours sur les règles indiquées dans le texte d'explication (correspondent pas à ce qui est indiqué dans le ticket, extrait du cahier des charges) : 

**"vous inviter à des événements"** : ça, ok. Lorsque qu'un bloqué créé un événement privé, le bloqueur n'apparait pas dans la liste des personnes qu'il peut inviter

**"voir votre profil"** : ça, c'est nouveau :) (c'est peut-être la formulation du ticket qui a prêté à confusion, j'ai corrigé)
- je ne vois pas quel est l'intérêt réel : un utilisateur ne peut de toute façon rien faire sur la page d'un profil, pas moyen de le contacter, etc. 
- difficilement faisable et complexe : est-ce que ça signifie que quand le bloqué regarde la page d'un événement, il ne voit pas le bloqueur dans la liste des participants ? Sauf qu'il peut s'inscrire quand même et alors ça entre en contradiction avec l'objectif, ou bien il peut pas et donc faut lui expliquer pourquoi et donc ça sert à rien de cacher le profil (cf remarques sur point suivant) ? 

**"s'inscrire à des événements auxquels vous participez"** : pas prévu non plus, et problématique. Comment justifier qu'on interdit l'accès à un événement à qqn sous prétexte que ça tête revient pas à un participant quelconque ? 
___

Par contre, **ce sur quoi on s'était arrêté** (je précise un peu plus, maintenant qu'on a le système définitif), c'est : 
- un bloqué ne voit pas dans la liste des événements les événements publics créés par un bloqueur
- si un bloqueur clique sur "participer" à un événement auquel un de ses bloqués participe déjà, il doit y avoir une pop up genre "Attention, Machin que vous avez bloqué participe déjà à l'événement. Confirmer votre participation ?")
- Si je suis participant à un événement, et qu’un bloqué s’inscrit ensuite, je reçois une notification.

**D'ailleurs, quoi comme notification ?**
- si le bloqueur est notifié que sur l'app (pas mail ni sms) -> signalement d'une façon où d'une autre sur la page d'un événement (triangle danger en rouge ? bandeau d'alerte ? @Gabriel-phi à la rescousse, si c'est bien ça)
- si notif sms (proposition) : "[Ensemble] Machin, que vous avez bloqué, vient de s'inscrire à l'événément [XXX] prévu le [XX]"
- si notif mail (proposition) : "Machin, que vous avez bloqué, vient de s'inscrire à l'événément [XXX] prévu le [XX] à [XXX], auquel vous êtes vous participez. Voir l'événement et géré ma participation _(lien vers la page de l'événement)_ "

**On est d'accord qu'un bloqué ne sait pas que quelqu'un l'a bloqué ?**

**Comment by clairezed** [comment]
Ci dessous, ce que j'ai mis pour le moment : 

"Si vous cliquez sur OK, cette personne ne pourra plus :
- vous inviter à des événements
- voir les événements que vous créez
Vous serez aussi informé si vous participez tous les deux au même événement."

**Comment by MIRADOR-EPINAL** [comment]
@clairezed 
Effectivement, on ne se rend pas toujours compte de ce qu'il y a sous le capot quand on écrit des trucs comme ça.
Partons sur ce que tu as fait et qui était convenu au départ.
Oui, bien entendu le bloqué n'est pas au courant que Machin ou Truc le bloque.

Oui pour tout ce que tu proposes là!!!

**D'ailleurs, quoi comme notification ?

    si le bloqueur est notifié que sur l'app (pas mail ni sms) -> signalement d'une façon où d'une autre sur la page d'un événement (triangle danger en rouge ? bandeau d'alerte ? @Gabriel-phi à la rescousse, si c'est bien ça)
    si notif sms (proposition) : "[Ensemble] Machin, que vous avez bloqué, vient de s'inscrire à l'événément [XXX] prévu le [XX]"
    si notif mail (proposition) : "Machin, que vous avez bloqué, vient de s'inscrire à l'événément [XXX] prévu le [XX] à [XXX], auquel vous êtes vous participez. Voir l'événement et gérer ma participation (lien vers la page de l'événement) "*
