### ISSUE TITLE
Utilisateur

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#2]
- [x] confirmation sms après inscription
- [x] confirmation sms après fin période libre
- [x] confirmation sms  dans édition profil
- [x] Formatage des numéro telephone pour Twilio
- [x] suppression profil
- [x] avatar
- [x] utilisateur miradorien
- [x] integration formulaires admin
- [x] Langues parlées
- [x] valider/revoir module d'upload image
- [x] Pays visités
- [x] Affichage loisirs sur profil
- [x] mettre un mailer devise fr (anglais en prod)

**Comment by clairezed** [comment]
@Gabriel-phi Dis, j'ai mis à jour en prod le module de choix de loisir et l'affichage des loisirs pour les utilisateurs. Sur les maquettes, on n'affichait que les grandes familles, donc là j'ai improvisé un affichage clairement pas abouti (en classant par grande famille, histoire qu'on capte les choix "Autre"). 

Cf http://ensemble.clairezuliani.com/profiles/2

Toute suggestion graphique est carrément bienvenue !

**Comment by clairezed** [comment]
@MIRADOR-EPINAL que s'est-on dit sur l'affichage des infos sur un profil utilisateur ? Si le champs est vide (par ex : "pays visités"), on n'affiche pas la rubrique ? (autres options : on affiche la rubrique avec rien (vide), ou avec "_non renseigné_")

**Comment by MIRADOR-EPINAL** [comment]
@clairezed Je crois bien qu'on n'est pas allé si loin. Mettons : on affiche le champ quand même avec un vide.
