### ISSUE TITLE
Commentaires

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#20]
- [x] Un utilisateur peut écrire un commentaire et est informé que son commentaire sera modéré a priori
- [x] Les commentaires acceptés sont affichés
- [x] L'organisateur est notifié lorsqu'un commentaire est publié sur son événement (à confirmer ?)
- [x] Admin est notifié d'un nouveau commentaire et peut l'accepter / le refuser
- [x] Admin peut lister et retrouver les commentaires "admin"

**Comment by clairezed** [comment]
@MIRADOR-EPINAL Je veux bien qu'on fasse un point sur les notifications, pour les commentaires (ci-dessous, points à confirmer ou infirmer)

1/ quand un nouveau commentaire  est créé : 
- l'admin reçoit un mail l'informant d'un commentaire à vérifier

2/ quand un commentaire est accepté par l'admin : 
- l'organisateur de l'événement reçoit une notification "Nouveau commentaire sur votre événement" (mail et/ou sms, suivant ce qu'il a coché)
- l'auteur du commentaire reçoit une notification "Commentaire accepté" (mail/sms) ?

3/ quand un commentaire est refusé par l'admin : 
- l'auteur du commentaire reçoit une notification "Commentaire refusé" (mail/sms) ?

**Comment by MIRADOR-EPINAL** [comment]
@clairezed **1/ quand un nouveau commentaire est créé 👍 
    l'admin reçoit un mail l'informant d'un commentaire à vérifier OUI

2/ quand un commentaire est accepté par l'admin 👍 
    l'organisateur de l'événement reçoit une notification "Nouveau commentaire sur votre événement" (mail et/ou sms, suivant ce qu'il a coché)** OUI
    l'auteur du commentaire reçoit une notification "Commentaire accepté" (mail/sms) ? NON, pas besoin

3/ quand un commentaire est refusé par l'admin :
l'auteurdu commentaire reçoit une notification "Commentaire refusé" (mail/sms) ? OK > a été ajouté dans  (https://docs.google.com/spreadsheets/d/1reVC2L9-lR4tCVZLD_V3J5xu291eJL53BdUI8k4gasg/edit#gid=1249544238) 
)
