### ISSUE TITLE
Grades utilisateurs

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#23]
CRITERES | débutant | habitué | expert | ambassadeur
|---|---|---|---|---|
nb de sorties auxquelles tu as réellement participées |   | 2 | 4 | 6
nb de sorties que tu as organisées et qui n'ont pas été annulées |   |   | 1 | 2
mail et téléphone vérifiés |   | X | X | X
présence de photo de profil |   |   | X | X

**Comment by clairezed** [comment]
@MIRADOR-EPINAL Pour précision (il me semble qu'on en avait déjà parlé) : vu que le grade dépend notamment de la bonne tenue d'événements passés (et qu'on ne sait pas forcément quand un événement est supposé être terminé), le changement de grade ne peut pas être instantané.

Je propose donc de mettre à jour automatiquement les grades une fois par jour, durant la nuit, en considérant que tous les événements non annulés ayant leur date de début à la veille (ou les jours d'avant) peuvent être pris en compte dans le calcul.

D'ailleurs, ce système de grade et son fonctionnement, ça fait partie des éléments qu'il faudra expliquer aux utilisateurs, aussi !

**Comment by MIRADOR-EPINAL** [comment]
@clairezed 
Partons là-dessus ok. ça va produire exactement ce qu'on recherche donc parfait!
