### ISSUE TITLE
Evénement - Supprimer le nombre de participant max pour les événements privés

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#31]
- choix du type d'évenement à faire + haut dans le formulaire
- suivant type d'évenement : apparition ou disparition du champs "nombre de participants max"
- supprimer la validation"encore de la place" pour les événements privés
- [x] affichage vignette -> supp nb
- [x] affichage fiche -> supp nb
- [x] pas d'affichage "événement complet"

OK - MIRADOR // >> la barre pour compter le nombre de personnes lors d'un événement public, la changer pour un champ de saisie nombre mini / nombre maxi

**Comment by MIRADOR-EPINAL** [comment]
C'est possible ou compliqué?

**Comment by clairezed** [comment]
@MIRADOR-EPINAL je ne comprends pas la demande... Je t'appelle mainteannt ? Dans l'aprem ?

**Comment by MIRADOR-EPINAL** [comment]
@clairezed  Cet aprem on n'est pas au bureau...
En fait, on est d'accord, dans l'événement privé on ne parle plus de nombre de participants, on supprime la barre.
Du coup, la demande concerne uniquement le formulaire de l'événement public. On laisse bien qqch pour mettre le nombre de participants mini et maxi. Sauf que la barre a été compliquée à utiliser pour qqs testeurs. Donc, je demandais si à la place de cette barre, il est possible de mettre un champ libre pour le nb mini de participants et pareil pour le nb maxi.
 @Gabriel-phi dit qu'a priori il y a moyen de trouver des astuces de mise en page de la barre pour que les utilisateurs comprennent mieux comment ça fonctionnent. 
Je vous laisse voir ça du coup. 
Pour l'instant, oublie mon histoire de champ libre....
