### ISSUE TITLE
Utilisateur - vérification : améliorer le processus de vérification post-inscription

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#57]
- Champs de saisi du code sms placé + haut
- modal de saisie du code sms après l'inscription

**Comment by clairezed** [comment]
@MIRADOR-EPINAL le contenu actuel de la modal d'accueil est minimaliste ("Bienvenue !" en titre ; puis le formulaire de saisie du num de tel). 

A tester et me dire les modifs éventuelles !

**Comment by MIRADOR-EPINAL** [comment]
@clairezed C'est quoi le modal d'accueil? Sur la landing page? Sorry, j'ai un problème de vocabulaire.

**Comment by clairezed** [comment]
A présent, à la fin de son inscription, un nouvel inscrit est envoyé sur la page d'accueil (avec les événements recommandés, mirador, etc). Pour l'amener à saisir le code reçu par sms, une modal (= pop up) s'ouvre sur cette page avec le champs de saisie du code.

Le mieux serait que tu te recréés un compte (quitte à supprimer un de tes anciens comptes en admin) pour pouvoir tester ce nouveau cheminement d'inscription.

**Comment by MIRADOR-EPINAL** [comment]
ok ça marche.
Merci de ta patience et de ta pédagogie!
