### ISSUE TITLE
Bouton "modifier mes paramètres" dans profil

### ISSUE THREAD

**Issue by MIRADOR-EPINAL** [clairezed/ensemble#61]
@clairezed Hey ! j'ai un doute, est-ce qu'on a bien dit qu'il fallait remonter le bouton "modifier mes paramètres" en dessus du titre "paramètre de contacts"?

**Comment by clairezed** [comment]
alors non (ou alors pas assez fort), mais ça parait tout à fait logique, donc il sera à remonter !

**Comment by MIRADOR-EPINAL** [comment]
@clairezed souuuuuupeeeeeerrrrr!!!
