### ISSUE TITLE
inscription par sms à un événement privé

### ISSUE THREAD

**Issue by MIRADOR-EPINAL** [clairezed/ensemble#67]
@clairezed J'ai créé un événement "aller manger une pizza à Bruxelles" j'ai invité Romain Carle. Il a reçu un sms et a répondu "oui 62". Mais son inscription n'est jamais apparu sur l'événement. C'est grave docteur?

**Comment by clairezed** [comment]
C'est tout a fait normal car il y a actuellement l'authentification en
place (login mirador, etc), qui bloque le von fonctionnement de twilio
l'envoyeur de SMS (dans la configuration actuelle, avec l'authentification,
il peut envoyer des SMS mais pas les recevoir, en gros).

**Comment by MIRADOR-EPINAL** [comment]
@clairezed  OKi douki. Donc ça veut dire que ce sera en place pour le 15 mars. Very good! Il faut que je fasse un truc pour twilio (en dehors de remettre de la tune dessus je veux dire)?

**Comment by clairezed** [comment]
Yep, ça a marché pdt les tests utilisateurs et rien n'a bougé depuis (j'ai
même reçu une notif de bug, comme attendu). Si besoin, pas de PB pour
rouvrir l'accès pour un vrai test.

Rien à faire de ton côté pour twilio !
