### ISSUE TITLE
Admin - changer le wysiwyg

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#68]
-> permet pas de copir-coller depuis un doc

**Comment by clairezed** [comment]
C'est bon, @MIRADOR-EPINAL , vous devriez pouvoir copier-coller. 
Notes : 
- ce qui apparait côté admin ne reflète pas la mise en page réelle, vérifier en front que la mise en forme est conforme à ce que vous voulez sans vous fier à ce que vous voyez dans le back office
- je n'ai pas activé toutes les options de mise en forme, je vous laisse me dire s'il manque des éléments

**Comment by MIRADOR-EPINAL** [comment]
@clairezed Bien reçu. Je teste ça et te redis.
