### ISSUE TITLE
page éditable "cookies"

### ISSUE THREAD

**Issue by MIRADOR-EPINAL** [clairezed/ensemble#69]
@clairezed 
Hey!
dans les pages éditables de l'admin (ouais ouais j'adore cette page!) il y en a une qui s'appelle cookies. Quand on va dans le bas du site, ce qui apparaît c'est "gérer les cookies" et c'est le formidable accès que tu as mis pour que l'utilisateur puisse changer d'avis à tout moment (franchement tu as grave assuré là dessus! il y aurait un prix CNIL, tu l'aurais. C'est au top).
Le blabla sur les cookies je l'ai intégré dans les CGU. Du coup, qu'est-ce qu'on fait de cette page éditable cookies? est-ce que j'y balance le blabla spécial cookies que j'ai mis dans les CGU?

**Comment by clairezed** [comment]
Bin, c'est comme vous voulez, y'a pas d'obligation de forme ! Le laïus cookie peut être une page dédiée, comme il peut être intégré dans les CGU, comme ça vous arrange. 

Le plus simple vu que c'est fait comme ça actuellement, c'est peut-être de garder les cookies dans les CGU et de virer la page éditable cookie ?

On fait ça ?

**Comment by MIRADOR-EPINAL** [comment]
@clairezed On fait ça!
