### ISSUE TITLE
Page accueil utilisateur connecté : Ordre affichage événement

### ISSUE THREAD

**Issue by clairezed** [clairezed/ensemble#8]
- [ ] : **« derniers événements » :**  ce sont les derniers événements postés et les plus proches de chez l’utilisateur logué

**Comment by clairezed** [comment]
@MIRADOR-EPINAL C'était les consignes données il y a quelques temps. Avec les retours utilisateurs des tests (confusion sur l'ordre d'affichage - y'avait un bug, c'est réparé), c'est confirmé ?

**Comment by MIRADOR-EPINAL** [comment]
@clairezed C'est vrai que ça a suscité des confusions. Est-ce que c'est possible qu'on revoit ça demain?

**Comment by clairezed** [comment]
-> prochains événements par date d'événement + proches géographiquement
